### ISSUE TITLE
PhysicalTableDefinition: build() should return an optional

### ISSUE THREAD

**Issue by kevinhinterlong** [yahoo/fili#249]
```java
/**
* ....
* @return optional of the corresponding type of physical table, empty optional if could not be build.
*/
public abstract PhysicalTable build(
    ResourceDictionaries dictionaries,
    DataSourceMetadataService metadataService
);
```
The comment says it should return an optional, but currently it's returning a `PhysicalTable`.
I'd change it but I'm not sure which was intended @cdeszaq

**Comment by cdeszaq** [comment]
This looks like a comment didn't get updated to match the implementation. At one point, the PR in which this was added had `build` returning an `Optional<PhysicalTable>` to allow the `build` method to fail to build the table in a way that didn't throw an exception, but it was changed because we couldn't think of a world in which an exception was less expressive than an empty Optional.

So, long-story-short, the _comment_ is what needs to be updated here, not the signature 😄

**Comment by cdeszaq** [comment]
Comments cleaned up in #252
